### ISSUE TITLE
초기 세팅 체크리스트

### ISSUE THREAD

**Issue by wjdrbs96** [mash-up-kr/SeeYouAgain_Spring#1]
- [x] Kotlin - Spring 멀티 모듈 프로젝트 Init 
- [x] Rest Docs 세팅 - 정균
- [x] yml 파일 암호화 jasypt 세팅 - 정균
- [x] AWS EC2, RDS 생성 - 세원
- [x] Exception 구조 및 ExceptionHandler 적용 - 정균
- [x] 테스트 코드 환경 구축 - 정균
- [x] domain yml 세팅 - 정균 ([PR Link](https://github.com/mash-up-kr/SeeYouAgain_Spring/pulls))
- [x] external 모듈 추가 - 정균
- [x] crawling 모듈 추가 - 도현

**Comment by K-Diger** [comment]
- [ ] Spring Boot 버전
