### ISSUE TITLE
크롤러 한 뉴스 키워드 추출에 관한 레퍼런스

### ISSUE THREAD

**Issue by K-Diger** [mash-up-kr/SeeYouAgain_Spring#25]
### Stack

- [Jsoup](https://jsoup.org/)
- [Lucene](https://mvnrepository.com/artifact/org.apache.lucene/lucene-core)
- [Lucene Korean Analyze](https://lucene.apache.org/core/7_4_0/analyzers-nori/org/apache/lucene/analysis/ko/KoreanAnalyzer.html)
- [Komoran](https://docs.komoran.kr/)

### 활용 1

-[Lucene Nori Korean Analze](https://m.blog.naver.com/websearch/221795964259)

1. Jsoup을 활용하여 뉴스 크롤링
2. News 저장
3. Lucene의 Analyzer를 활용하여 키워드 추출
4. NewsCard 저장

### 활용 2 - 채택

1. Jsoup을 활용하여 뉴스 크롤링
2. News 저장
3. Komoran의 한국어 형태소 분석기를 활용하여 키워드 추출
4. NewsCard 저장

---

본문의 내용 중 정확도가 더 높아 보이는 오픈소스를 활용하기로 결정하여 Komoran을 채택합니다.

판단 근거) 최저임금에 관한 기사를 키워드로 요약할 시 Apache Lucene은 아래와 같이

최저, 임금 ... 으로 "최저임금"이라는 적합한 키워드로 추출하지 못하였으나 Komoran은 "최저임금"을 키워드로 추출할 수 있었습니다.

![image](https://github.com/mash-up-kr/SeeYouAgain_Spring/assets/60564431/7f3765b8-a674-479d-a840-9119cd914034)

**Comment by wjdrbs96** [comment]
- 키워드 추출을 개발하면서 어떤 고민을 했고, 어떤 라이브러리가 선택지에 있었고, 그 중에서 선택한 것을 왜 선택했는지의 과정에 대한 정리 ?
